version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.1
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:$MAILMANDBPASS@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=$HYPERKITTYAPIKEY
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    ports:
      - "8024:8024"
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.1
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - SERVE_FROM_DOMAIN=mailman.education.gov.il
    - DATABASE_TYPE=postgres
    - DATABASE_URL="postgres://mailman:$MAILMANDBPASS@database/mailmandb"
    - HYPERKITTY_API_KEY="somekey"
    - SECRET_KEY='somesecret'
    - MAILMAN_ADMIN_USER='admin'
    - MAILMAN_ADMIN_EMAIL='asaf@sysbind.co.il'
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: $MAILMANDBPASS
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.19.199.4

  nginx:
    restart: always
    image: nginx
    volumes:
      - /opt/mailman/web/static:/usr/share/nginx/html/static
      - ./nginx-uwsgi.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      mailman:
        ipv4_address: 172.19.199.9
        
networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       -
         subnet: 172.19.199.0/24
